name: Blue-Green Deployment

on:
    push:  # This will trigger the workflow on push events
      branches:
        - main  # Specify the branch to listen for pushes. Change as needed.
    pull_request:
      types: [opened, synchronize, reopened]
    schedule:
      - cron: '0 0 * * *' # This runs every day at 00:00 UTC
    workflow_dispatch: # Manual trigger

jobs:
  deploy:
    runs-on: self-hosted  # Use your self-hosted runner
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
     
    - name: log in to duckerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
    - name: Build Application
      run: |
         docker build -t i533542/test01 ./
         echo "Building the application..."


    - name: Push to Docker Hub
      run: |
        docker push i533542/test01
        echo "Pushing the image to Docker Hub..."


    - name: Deploy to Remote Server
      run: |
        ssh -o StrictHostKeyChecking=no student@172.16.2.43 << 'EOF'
          docker pull i533542/test01  # Pull the image on the remote Docker server
          docker-compose down  # Stop the current running containers
          docker-compose up -d  # Start the new containers
        EOF
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

        
    # - name: Run Tests
    #   run: |
    #     # Add your test commands here
    #     echo "Running tests..."

    # - name: Deploy to Inactive Environment
    #   run: |
    #     # Add commands to deploy to the green environment (inactive)
    #     echo "Deploying to inactive environment..."

    # - name: Await Approval for Production
    #   id: approval
    #   run: |
    #     echo "Waiting for approval..."
    #     # Simulate waiting for approval
    #     # You could implement a check here based on your approval process

    # - name: Switch to Active Environment
    #   if: steps.approval.outputs.approved == 'true' # Check if approved
    #   run: |
    #     echo "Switching to the inactive environment (now active)..."
    #     # Add commands to switch the routing in HAProxy or your load balancer 
